kind: Service
apiVersion: v1
metadata:
  name: message-broker
  labels:
    app: message-broker
spec:
  type: NodePort
  # externalTrafficPolicy: Local
  ports:
  - port: 5672
    name: amqp
    protocol: TCP
    targetPort: 5672
    nodePort: 31011
  - port: 15672
    name: http
    protocol: TCP
    targetPort: 15672
    nodePort: 31012
  - port: 1883
    name: mqtt
    protocol: TCP
    targetPort: 1883
    nodePort: 31013
  - port: 61613
    name: stomp
    protocol: TCP
    targetPort: 61613
    nodePort: 31014
  selector:
    app: message-broker
